apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: poonamkumar123/my-django-image:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
