apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: mydatabase
        resources:
          requests:
            memory: "256Mi"  # Adjust the values based on your requirements
            cpu: "250m"
          limits:
            memory: "512Mi"  # Adjust the values based on your requirements
            cpu: "500m"
